#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DataAccess.Resource", IsApplication=false)]

namespace DataAccess
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public static int slide_in_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int slide_out_left = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public static int font = 2130771975;
			
			// aapt resource value: 0x7f010000
			public static int fontProviderAuthority = 2130771968;
			
			// aapt resource value: 0x7f010003
			public static int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7f010004
			public static int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7f010005
			public static int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7f010001
			public static int fontProviderPackage = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int fontProviderQuery = 2130771970;
			
			// aapt resource value: 0x7f010006
			public static int fontStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public static int fontWeight = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f090000
			public static int abc_action_bar_embed_tabs = 2131296256;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060003
			public static int notification_action_color_filter = 2131099651;
			
			// aapt resource value: 0x7f060004
			public static int notification_icon_bg_color = 2131099652;
			
			// aapt resource value: 0x7f060000
			public static int notification_material_background_media_default_color = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int primary_text_default_material_dark = 2131099649;
			
			// aapt resource value: 0x7f060005
			public static int ripple_material_light = 2131099653;
			
			// aapt resource value: 0x7f060002
			public static int secondary_text_default_material_dark = 2131099650;
			
			// aapt resource value: 0x7f060006
			public static int secondary_text_default_material_light = 2131099654;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0a0004
			public static int compat_button_inset_horizontal_material = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public static int compat_button_inset_vertical_material = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public static int compat_button_padding_horizontal_material = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public static int compat_button_padding_vertical_material = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public static int compat_control_corner_material = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public static int notification_action_icon_size = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public static int notification_action_text_size = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public static int notification_big_circle_margin = 2131361803;
			
			// aapt resource value: 0x7f0a0001
			public static int notification_content_margin_start = 2131361793;
			
			// aapt resource value: 0x7f0a000c
			public static int notification_large_icon_height = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public static int notification_large_icon_width = 2131361805;
			
			// aapt resource value: 0x7f0a0002
			public static int notification_main_column_padding_top = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public static int notification_media_narrow_margin = 2131361795;
			
			// aapt resource value: 0x7f0a000e
			public static int notification_right_icon_size = 2131361806;
			
			// aapt resource value: 0x7f0a0000
			public static int notification_right_side_padding_top = 2131361792;
			
			// aapt resource value: 0x7f0a000f
			public static int notification_small_icon_background_padding = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public static int notification_small_icon_size_as_large = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public static int notification_subtext_size = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public static int notification_top_pad = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public static int notification_top_pad_large_text = 2131361811;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int ic_arrow_back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int notification_action_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int notification_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int notification_bg_low = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int notification_bg_low_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int notification_bg_low_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int notification_bg_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int notification_bg_normal_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int notification_icon_background = 2130837512;
			
			// aapt resource value: 0x7f02000b
			public static int notification_template_icon_bg = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int notification_template_icon_low_bg = 2130837516;
			
			// aapt resource value: 0x7f020009
			public static int notification_tile_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int notify_panel_notification_icon_bg = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b000e
			public static int action0 = 2131427342;
			
			// aapt resource value: 0x7f0b000b
			public static int action_container = 2131427339;
			
			// aapt resource value: 0x7f0b0012
			public static int action_divider = 2131427346;
			
			// aapt resource value: 0x7f0b000c
			public static int action_image = 2131427340;
			
			// aapt resource value: 0x7f0b000d
			public static int action_text = 2131427341;
			
			// aapt resource value: 0x7f0b001c
			public static int actions = 2131427356;
			
			// aapt resource value: 0x7f0b0005
			public static int async = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public static int blocking = 2131427334;
			
			// aapt resource value: 0x7f0b000f
			public static int cancel_action = 2131427343;
			
			// aapt resource value: 0x7f0b0017
			public static int chronometer = 2131427351;
			
			// aapt resource value: 0x7f0b001e
			public static int end_padder = 2131427358;
			
			// aapt resource value: 0x7f0b0007
			public static int forever = 2131427335;
			
			// aapt resource value: 0x7f0b0019
			public static int icon = 2131427353;
			
			// aapt resource value: 0x7f0b001d
			public static int icon_group = 2131427357;
			
			// aapt resource value: 0x7f0b0018
			public static int info = 2131427352;
			
			// aapt resource value: 0x7f0b0008
			public static int italic = 2131427336;
			
			// aapt resource value: 0x7f0b0000
			public static int line1 = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public static int line3 = 2131427329;
			
			// aapt resource value: 0x7f0b0011
			public static int media_actions = 2131427345;
			
			// aapt resource value: 0x7f0b0009
			public static int normal = 2131427337;
			
			// aapt resource value: 0x7f0b001b
			public static int notification_background = 2131427355;
			
			// aapt resource value: 0x7f0b0014
			public static int notification_main_column = 2131427348;
			
			// aapt resource value: 0x7f0b0013
			public static int notification_main_column_container = 2131427347;
			
			// aapt resource value: 0x7f0b001a
			public static int right_icon = 2131427354;
			
			// aapt resource value: 0x7f0b0015
			public static int right_side = 2131427349;
			
			// aapt resource value: 0x7f0b0010
			public static int status_bar_latest_event_content = 2131427344;
			
			// aapt resource value: 0x7f0b0002
			public static int text = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public static int text2 = 2131427331;
			
			// aapt resource value: 0x7f0b0016
			public static int time = 2131427350;
			
			// aapt resource value: 0x7f0b0004
			public static int title = 2131427332;
			
			// aapt resource value: 0x7f0b000a
			public static int webview = 2131427338;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public static int cancel_button_image_alpha = 2131165184;
			
			// aapt resource value: 0x7f070001
			public static int status_bar_notification_info_maxnum = 2131165185;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int activity_webview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int notification_action = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int notification_action_tombstone = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int notification_media_action = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int notification_media_cancel_action = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int notification_template_big_media = 2130903045;
			
			// aapt resource value: 0x7f030006
			public static int notification_template_big_media_custom = 2130903046;
			
			// aapt resource value: 0x7f030007
			public static int notification_template_big_media_narrow = 2130903047;
			
			// aapt resource value: 0x7f030008
			public static int notification_template_big_media_narrow_custom = 2130903048;
			
			// aapt resource value: 0x7f030009
			public static int notification_template_custom_big = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public static int notification_template_icon_group = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public static int notification_template_lines_media = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public static int notification_template_media = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public static int notification_template_media_custom = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public static int notification_template_part_chronometer = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public static int notification_template_part_time = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080002
			public static int ApplicationName = 2131230722;
			
			// aapt resource value: 0x7f080001
			public static int Hello = 2131230721;
			
			// aapt resource value: 0x7f080004
			public static int library_name = 2131230724;
			
			// aapt resource value: 0x7f080000
			public static int status_bar_notification_info_overflow = 2131230720;
			
			// aapt resource value: 0x7f080003
			public static int title_activity_webview = 2131230723;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050005
			public static int TextAppearance_Compat_Notification = 2131034117;
			
			// aapt resource value: 0x7f050006
			public static int TextAppearance_Compat_Notification_Info = 2131034118;
			
			// aapt resource value: 0x7f050000
			public static int TextAppearance_Compat_Notification_Info_Media = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public static int TextAppearance_Compat_Notification_Line2 = 2131034123;
			
			// aapt resource value: 0x7f050004
			public static int TextAppearance_Compat_Notification_Line2_Media = 2131034116;
			
			// aapt resource value: 0x7f050001
			public static int TextAppearance_Compat_Notification_Media = 2131034113;
			
			// aapt resource value: 0x7f050007
			public static int TextAppearance_Compat_Notification_Time = 2131034119;
			
			// aapt resource value: 0x7f050002
			public static int TextAppearance_Compat_Notification_Time_Media = 2131034114;
			
			// aapt resource value: 0x7f050008
			public static int TextAppearance_Compat_Notification_Title = 2131034120;
			
			// aapt resource value: 0x7f050003
			public static int TextAppearance_Compat_Notification_Title_Media = 2131034115;
			
			// aapt resource value: 0x7f050009
			public static int Widget_Compat_NotificationActionContainer = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public static int Widget_Compat_NotificationActionText = 2131034122;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public static int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public static int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public static int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public static int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public static int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public static int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 1
			public static int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public static int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public static int FontFamilyFont_fontWeight = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
